package lotto.domain;

import lotto.util.ExceptionUtils;

public class Lotto {
	private boolean autoGeneratedFlag;
	private LottoNumbers lottoNumbers;
	
	public static final int LOTTO_PRICE = 1000;
	public static final int LOTTO_NUMBERS_SIZE = 6;
	
	public Lotto(LottoNumbers lottoNumbers, boolean autoGeneratedFlag) {
		validateLottoNumbers(lottoNumbers);
		this.lottoNumbers = lottoNumbers;
		this.autoGeneratedFlag = autoGeneratedFlag;
	}
	
	public LottoNumbers getLottoNumbers() {
		return lottoNumbers;
	}

	public boolean contains(LottoNumber lottoNumber) {
		return lottoNumbers.contains(lottoNumber);
	}
	
	public boolean isAutoGenerated() {
		return autoGeneratedFlag;
	}
	
	private void validateLottoNumbers(LottoNumbers lottoNumbers) {
		if(lottoNumbers.size() != LOTTO_NUMBERS_SIZE) {
			ExceptionUtils.throwIllegalArgumentException(Lotto.class, "Lotto는 6개의 번호를 가져야 합니다.");
		}
	}
}
